### ISSUE TITLE
Add support to glass Web UI

### ISSUE THREAD

**Issue by lexcorp** [vyos/vyos-rolling-nightly-builds#1]
Add support to glass Web UI like this:

https://github.com/Akkadius/glass-isc-dhcp

Examples:

https://user-images.githubusercontent.com/3319450/31204215-6b805826-a930-11e7-8e07-4731c958bda4.gif

https://user-images.githubusercontent.com/3319450/31204509-bb583c00-a931-11e7-982c-186ef8c33e61.gif

**Comment by sarthurdev** [comment]
Please file feature requests/issues on https://vyos.dev
